[dependencies]
base = "0.10.1"
uuid = "0.1.0"
itertools = "0.1.1"
stable-hash-map = "0.2.1"
sha2 = "0.0.4"
json = "0.2.0"

[package]
name = "lnft"
version = "0.1.0"
description = "Living NFT System"
repository = ""
keywords = [ "nft", "ic", "neural" ]